# Generated by Django 4.2.8 on 2023-12-29 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_restaurant_post_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='address2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
