# Generated by Django 4.2.8 on 2023-12-29 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_restaurant_address2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='restaurant_id',
        ),
    ]
